beatles_logo:
  title: "KAOS THE BEATLES LOGO"
  sku: "beatles-logo"
  bahan_kaos: "New States Apparel Soft Tee, Combed 30s"
  harga: "Rp 99,000"
  shopee_url: "https://shopee.co.id/bayualdi/3114253553"
  image_name: "post-the-beatles-logo.png"
